spring:
  datasource:
    url: http://localhost:3306/test/
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate.hbm2ddl.auto: create-drop
    show-sql: true